#!/bin/sh

CONTAINER_NAME="$(basename $(dirname ${BASH_SOURCE[0]}))"
CONTAINER_OUTPUT="/u/containers/$CONTAINER_NAME"
CONTAINER_SOURCE=

# Embed into an initramfs
DO_EMBED=true

# Build an ISO for testing purposes
DO_GENERATE_ISO=true

DISTRO=trusty

PROFILE=ubuntu

# Sets up the default packages to install
PACKAGES="iproute2,net-tools,ifupdown,iputils-ping,bind9-host,ntp,ntpdate,ubuntu-minimal,ubuntu-standard,curl,ca-certificates,wget"

# Extra packages to be installed after debootstrap
EXTRA_PACKAGES="openssh-server lvm2 parted mdadm grub-pc vim dmidecode pciutils binutils util-linux squashfs-tools initramfs-tools live-boot ipmitool"

EXCLUDE_PATTERN=()

# Packages to blacklist during debootstrap
BLACKLIST_PACKAGES=""

KERNEL_ARGS="installtodisk"

customize(){
  # Get ruby
  echo "deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu ${DISTRO} main " >> "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/etc/apt/sources.list"
  cexec sudo gpg --keyserver keyserver.ubuntu.com --recv C3173AA6
  cexec sudo apt-get update
  cexec sudo apt-get install -y --force-yes ruby2.3 ruby-switch
  cexec sudo ruby-switch --set ruby2.3

  # Get megacli
  cexec sudo curl http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key -o /tmp/megaraid_gpg
  cexec sudo apt-key add /tmp/megaraid_gpg
  echo 'deb http://hwraid.le-vert.net/debian jessie main' >> "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/etc/apt/sources.list"
  cexec sudo apt-get update
  cexec sudo apt-get install -y --force-yes megacli


  echo "deb http://ppa.launchpad.net/ubuntu-lxc/stable/ubuntu ${DISTRO} main" >> "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/etc/apt/sources.list"
  cexec sudo gpg --keyserver keyserver.ubuntu.com --recv 7635B973
  #cexec gpg --export --armor 7635B973 | sudo apt-key add -
  cexec sudo apt-get update

  cat > "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/usr/sbin/policy-rc.d" << EOF
#!/bin/sh
echo "All runlevel operations denied by policy" >&2
exit 101
EOF
  cexec chmod a+x /usr/sbin/policy-rc.d
  cexec apt-get install -y --force-yes lxc
  cexec apt-get install -y linux-generic-lts-vivid
  rm "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/usr/sbin/policy-rc.d"


  ONBOOT_PATH="/etc/lxb_onboot_script"
  cat > "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/${ONBOOT_PATH}" << 'EOF'
#!/bin/bash
set -e
set -x

wait_network()
{
  MAX_RETRIES=20
  retries=0
  echo "Waiting for network"
  while [ -z "$(ip route | grep 'default' | awk '{print $3}')" ];do
    ip="$(ip route | grep 'default' | awk '{print $3}')"
    if [ -n "${ip}" ];then
      ping -t 1 -c 1 ${ip} > /dev/null
      [ $? -eq 0 ] && break
    fi
    retries=$[$retries +1]
    if [ $retries -gt $MAX_RETRIES ];then
      echo "Network failed to come up"
      exit 1
    fi
    sleep 5
  done
  echo "Network is up"
}

wait_network
# Fetch and run script at onboot_script_url if given
if [ -n "$(grep onboot_script_url= /proc/cmdline)" ];then

  # Read the script URL from /proc/cmdline
  url_param=$(grep -o 'onboot_script_url=\S*' /proc/cmdline)
  url=${url_param#onboot_script_url=}

  curl $url > /onboot_script
  chmod +x /onboot_script

  /onboot_script

fi
exit 0
EOF

  cat > "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/etc/init/onboot_script.conf" << EOF
start on (started networking)

script
  ${ONBOOT_PATH}
end script
EOF

  cexec chmod +x ${ONBOOT_PATH}

}
